version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      #- AWS_DEFAULT_REGION=us-east-1
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - REPOSITORY_URI=663668850653.dkr.ecr.us-east-1.amazonaws.com/sdc-airflow:latest
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t docker-whale .
      - docker tag docker-whale:latest $REPOSITORY_URI      
  post_build:
    commands:
      - docker images
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $REPOSITORY_URI   



