FROM busybox

LABEL maintainer="christoph@wempe.net"

# sleep forever
#CMD tail -f /dev/null
CMD [ "ps", "faux" ]


#FROM puckel/docker-airflow:1.10.6
#RUN pip install --user psycopg2-binary
##COPY config/airflow/airflow.cfg usr/local/airflow/airflow.cfg
